---
output:
  word_document: default
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

#Import dataset
```{r, echo=FALSE}
library(caret)
library(GGally)
library(cluster)


setwd("~/GitHub/MultivariantAnalysis_IBMDataset/")
load("./Data/df_preprocessed_IBM_Employees.Rdata") 
names(df) 

```

#0 eliminate irrelevant columns
```{r, echo=FALSE}
colnames(df)

df<-subset(df, select = c(Age,Gender,Education, JobInvolvement, JobSatisfaction, OverTime,TotalWorkingYears, PerformanceRating))

colnames(df)

```


# 1 transform numerical variables (normalize and scale)
```{r, echo=FALSE}

df_trans <- df


hist(df$Age) # normalize(scale)
hist(scale(df$Age))

hist(df$TotalWorkingYears) # log 
hist(log(df$TotalWorkingYears))
df_trans$TotalWorkingYears <- log(df$TotalWorkingYears+1)

df_norm<-df_trans

range01 <- function(x){(x-min(x))/(max(x)-min(x))}

df_norm[,c(1)] <- range01(df_trans[,c(1)])
df_norm[,c(7)] <- range01(df_trans[,c(7)])


boxplot(df_norm[,c(1,7)])

```


# 3 Clustering 2
```{r, echo=FALSE}

#dissimilarity matrix
colnames(df_norm[,c(1:4,6)])

p<-c(5,1,1.7,1.5,1.5)
dissimMatrix <- daisy(df_norm[,c(1:4,6)], metric = "gower",weights = p,  stand=TRUE)
distMatrix<-dissimMatrix^2

h1<-hclust(distMatrix,method="ward.D")

options(max.print=2000)
options(scipen=999)
h1$height

plot(h1) 

rect.hclust(h1, h=18.1290048755   , border="red") # 2 clusters

rect.hclust(h1, h=27   , border="blue") # 4 clusters

c2<-cutree(h1,6)
df_norm$clust<-as.factor(c2)

#plot results
ggpairs(df_norm[,c(1:3,9)], columns = c(1:4), aes(color = clust, alpha = 0.5),progress = FALSE)
ggpairs(df_norm[,c(4,6,9)], columns = c(1:3), aes(color = clust, alpha = 0.5),progress = FALSE)

ggpairs(df_norm[,c(1,9)], columns = c(1:2), aes(color = clust, alpha = 0.5),progress = FALSE)



```



### 4 clusters

```{r, echo=FALSE}
total <- sum(table(df_norm$clust))
100*table(df_norm$clust)[1]/total 
100*table(df_norm$clust)[2]/total 
100*table(df_norm$clust)[3]/total 
100*table(df_norm$clust)[4]/total 
100*table(df_norm$clust)[5]/total 
100*table(df_norm$clust)[6]/total 

table(df_norm$Education)
ggplot(df_norm[,c(1:4,6,9)], aes(x= Education,  group=clust)) + 
    geom_bar(aes(y = ..prop.., fill = factor(..x..,labels = c("Below College" ,      "College"  ,    "Bachelor"   ,     "Master" ,       "Doctor"))), stat="count") +
    geom_text(aes( label = scales::percent(..prop..),
                   y= ..prop.. ), stat= "count", vjust = -.5) +
    labs(y = "Percent", fill="Education") +
    facet_grid(~clust) +
    scale_y_continuous(labels = scales::percent)

table(df_norm$OverTime)
ggplot(df_norm[,c(1:4,6,9)], aes(x= OverTime,  group=clust)) + 
    geom_bar(aes(y = ..prop.., fill = factor(..x..,labels = c("No" , "Yes"))), stat="count") +
    geom_text(aes( label = scales::percent(..prop..),
                   y= ..prop.. ), stat= "count", vjust = -.5) +
    labs(y = "Percent", fill="OverTime") +
    facet_grid(~clust) +
    scale_y_continuous(labels = scales::percent)

table(df_norm$JobInvolvement)
ggplot(df_norm[,c(1:4,6,9)], aes(x= JobInvolvement,  group=clust)) + 
    geom_bar(aes(y = ..prop.., fill = factor(..x..,labels = c("Low" ,  "Medium" ,     "High", "Very High"))), stat="count") +
    geom_text(aes( label = scales::percent(..prop..),
                   y= ..prop.. ), stat= "count", vjust = -.5) +
    labs(y = "Percent", fill="JobInvolvement") +
    facet_grid(~clust) +
    scale_y_continuous(labels = scales::percent)

table(df_norm$Gender)
ggplot(df_norm[,c(1:4,6,9)], aes(x= Gender,  group=clust)) + 
    geom_bar(aes(y = ..prop.., fill = factor(..x..,labels = c("Female",   "Male"))), stat="count") +
    geom_text(aes( label = scales::percent(..prop..),
                   y= ..prop.. ), stat= "count", vjust = -.5) +
    labs(y = "Percent", fill="Gender") +
    facet_grid(~clust) +
    scale_y_continuous(labels = scales::percent)

#plot results
ggpairs(df_norm, columns=c(1:4), aes(color = clust, alpha = 0.5),progress = FALSE)
ggpairs(df_norm, columns=c(5:8), aes(color = clust, alpha = 0.5),progress = FALSE)
ggpairs(df_norm, columns=c(9:12), aes(color = clust, alpha = 0.5),progress = FALSE)
ggpairs(df_norm, columns=c(13:16), aes(color = clust, alpha = 0.5),progress = FALSE)


p <- ggplot(df, aes(x=Age, y=OverTime)) + 
  geom_boxplot()
p


hist(df[df$OverTime == "Yes",]$Age)
hist(df[df$OverTime == "No",]$Age)

100 * table(df$Age,df$OverTime)[,2]/(table(df$Age,df$OverTime)[,1] + table(df$Age,df$OverTime)[,2])


df$clust <- df_norm$clust

hist(df[df$clust == 2,]$Age)
hist(df[(df$clust == 2) & (df$Age > 45),]$MonthlyIncome)
hist(df[(df$clust == 5) & (df$Age > 45),]$MonthlyIncome)



table(df$OverTime)



```

