---
output:
  word_document: default
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

#Import dataset

```{r, echo=FALSE}
library(caret)
library(GGally)
library(cluster)


load("./Data/df_preprocessed_IBM_Employees.Rdata") 
names(df) 

```

# 0 - Get relevant columns

```{r, echo=FALSE}
colnames(df)

df<-subset(df, select = c(EnvironmentSatisfaction, JobInvolvement, WorkLifeBalance, OverTime, PerformanceRating,SalaryHikePerYear)) # he tret stockoption level, crec que millora cluster

colnames(df)

```

# 1 transform numerical variables (normalize and scale)

```{r, echo=FALSE}

df_trans <- df

hist(df$SalaryHikePerYear) # log 
hist(log(df$SalaryHikePerYear))
df_trans$SalaryHikePerYear <- log(df$SalaryHikePerYear+1)

df_norm<-df_trans

range01 <- function(x){(x-min(x))/(max(x)-min(x))}
df_norm[,c(6)] <- range01(df_trans[,c(6)])



```

# 2 transform categorical variables

```{r, echo=FALSE}

df_norm[,c(1)] <- range01(as.numeric(df_trans[,c(1)]))
df_norm[,c(2)] <- range01(as.numeric(df_trans[,c(2)]))
df_norm[,c(3)] <- range01(as.numeric(df_trans[,c(3)]))
df_norm[,c(4)] <- range01(as.numeric(df_trans[,c(4)]))
df_norm[,c(5)] <- range01(as.numeric(df_trans[,c(5)]))

colnames(df_norm)
boxplot(df_norm) 

```

# 3 Clustering

```{r, echo=FALSE}

#dissimilarity matrix
dissimMatrix <- daisy(df_norm, metric = "gower", stand=TRUE)
distMatrix<-dissimMatrix^2

h1<-hclust(distMatrix,method="ward.D")
options(max.print=2000)
options(scipen=999)
h1$height
plot(h1)
rect.hclust(h1, h=4.676613432883569,border="green") # 7 clusters
rect.hclust(h1, h=8.836629913913978,border="red") # 5 clusters
rect.hclust(h1, h=42.539874590219476,border="blue") # 3 clusters

c1<-cutree(h1,3)
df$cluster<-c1

cdg <- aggregate(as.data.frame(df_norm),list(c1),mean) 
cdg



c2<-cutree(h1,3)
df_norm$clust<-as.factor(c2)
#plot results
ggpairs(df_norm, columns = c(1:3), aes(color = clust, alpha = 0.5),progress = FALSE)
ggpairs(df_norm, columns = c(4:6), aes(color = clust, alpha = 0.5),progress = FALSE)

c2<-cutree(h1,5)
df_norm$clust<-as.factor(c2)
#plot results
ggpairs(df_norm, columns = c(1:3), aes(color = clust, alpha = 0.5),progress = FALSE)
ggpairs(df_norm, columns = c(4:6), aes(color = clust, alpha = 0.5),progress = FALSE)

c2<-cutree(h1,7)
df_norm$clust<-as.factor(c2)
#plot results
ggpairs(df_norm, columns = c(1:3), aes(color = clust, alpha = 0.5),progress = FALSE)
ggpairs(df_norm, columns = c(4:6), aes(color = clust, alpha = 0.5),progress = FALSE)

```
