---
output:
  word_document: default
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

# Import dataset and libraries

```{r, echo=FALSE}
library(caret)
library(GGally)
library(cluster)


load("./Data/df_preprocessed_IBM_Employees.Rdata") 
names(df) 

```

# 0 - Delete irrelevant columns

```{r, echo=FALSE}
colnames(df)
dcat<-df[!sapply(df, is.factor)]

colnames(dcat)

colnames(dcat[,c(1,4,6,7,8,10,14,15)])

df_red <- dcat[,c(1,4,6,7,8,10,14,15)]

```

# 1 - Transform variables (normalize and scale)

```{r, echo=FALSE}

df_trans <- df_red


hist(df_red$Age) # normalize(scale)
hist(scale(df_red$Age))

hist(df_red$MonthlyIncome, breaks = 20) # create quantiles ?

hist(df_red$NumCompaniesWorked) 

hist(df_red$PercentSalaryHike) 

hist(df_red$TotalWorkingYears) # create quantiles ? 

hist(df_red$YearsAtCompany) # log 
hist(log(df_red$YearsAtCompany))
df_trans$YearsAtCompany <- log(df_red$YearsAtCompany+1)

hist(df_red$SalaryHikePerYear) # log 
hist(log(df_red$SalaryHikePerYear))
df_trans$SalaryHikePerYear <- log(df_red$SalaryHikePerYear)

hist(df_red$AverageYearsCompany) # log 
hist(log(df_red$AverageYearsCompany))
df_trans$AverageYearsCompany <- log(df_red$AverageYearsCompany)

df_norm<-df_trans

range01 <- function(x){(x-min(x))/(max(x)-min(x))}

for(i in colnames(df_trans)){
  df_norm[,i] <- range01(df_trans[,i])
}


boxplot(df_norm)

```

# 2 - Results from numerical transformed variables

```{r, echo=FALSE}
#types of distances: "euclidean", "maximum", "manhattan", "canberra", "binary"
#types of methods for clustering "ward.D", "ward.D2", "single", "complete", "average" (= UPGMA), "mcquitty" (= WPGMA), "median" (= WPGMC) or "centroid" (= UPGMC).

d<-dist(df_norm,method = "euclidean") 
h1<- hclust(d,method="ward.D")
plot(h1)

c2<-cutree(h1,4)
df_norm$clust<-as.factor(c2)

colnames(df_norm)

df_norm$Attrition <- df$Attrition

ggpairs(df_norm, columns = c(1:4), aes(color = clust, alpha = 0.5),progress = FALSE)
ggpairs(df_norm, columns = c(5:8), aes(color = clust, alpha = 0.5),progress = FALSE)

pairs(df_norm[,1:8])

```

# 3 add categorical variables

```{r, echo=FALSE}
library(cluster)

#Take all the categorical variables into dcategoriques and delete the usless variables
dcategoriques<-df[sapply(df, is.factor)]
dcategoriques<-subset(dcategoriques, select = -c(Attrition,DistanceFromHome,Education, EducationField, JobLevel, JobRole))
names(dcategoriques)

#join the dcategoriques with the filtered df_norm into a new df ->df_join
colnames(df_norm)

df_join <- df_norm[,c(1:8)]

for(i in colnames(dcategoriques)){
  df_join[,i] <- dcategoriques[,i]  
}


#dissimilarity matrix
dissimMatrix <- daisy(df_join, metric = "gower", stand=TRUE)
distMatrix<-dissimMatrix^2
distMatrix
h1<-hclust(distMatrix,method="ward.D")
plot(h1) 
c2<-cutree(h1,2)
df_join$clust<-as.factor(c2)

# Visualitzations
boxplot(df_join$Attrition~c2)
boxplot(df_join$MonthlyIncome~c2, horizontal=TRUE)

colnames(df_join)

ggpairs(df_join, columns = c(1:5), aes(color = clust, alpha = 0.5),progress = FALSE)
ggpairs(df_join, columns = c(6:10), aes(color = clust, alpha = 0.5),progress = FALSE)
ggpairs(df_join, columns = c(11:15), aes(color = clust, alpha = 0.5),progress = FALSE)
ggpairs(df_join, columns = c(16:20), aes(color = clust, alpha = 0.5),progress = FALSE)
ggpairs(df_join, columns = c(21:24), aes(color = clust, alpha = 0.5),progress = FALSE)


df$RelationshipSatisfaction
colnames(df)
```




EnvironmentSatisfaction
JobInvolvement
WorkLifeBalance
OverTime
PerformanceRating
SalaryHikePerYear
StockOptionLevelS



